# Generated by Django 3.0.3 on 2020-02-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=10)),
                ('shorthand', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=20)),
                ('semester', models.TextField(choices=[('1', '1'), ('2', '1/2'), ('3', '2'), ('4', '2/3'), ('5', '3'), ('6', '1/2/3')], max_length=1)),
                ('elective', models.TextField(choices=[('1', 'NE'), ('2', 'PE'), ('3', 'EO')], max_length=1)),
                ('level', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('9', '9')], max_length=1)),
                ('aims', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.TextField(blank=True, default='')),
                ('syllabus', models.TextField(blank=True, default='')),
                ('criteria', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('reading', models.TextField(blank=True, default='')),
                ('lecture_hours', models.IntegerField(default=0)),
                ('tutorial_hours', models.IntegerField(default=0)),
                ('assignment_hours', models.IntegerField(default=0)),
                ('lab_hours', models.IntegerField(default=0)),
                ('study_hours', models.IntegerField(default=0)),
                ('required_modules', models.ManyToManyField(blank=True, related_name='requirements', to='MDFDatabase.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('forename', models.TextField()),
                ('surname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(choices=[('1', '1'), ('2', '1/2'), ('3', '2'), ('4', '2/3'), ('5', '3'), ('6', '1/2/3')], max_length=1)),
                ('week', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', 'Exam Period')], max_length=2)),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDFDatabase.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(choices=[('1', '1'), ('2', '1/2'), ('3', '2'), ('4', '2/3'), ('5', '3'), ('6', '1/2/3')], max_length=1)),
                ('week', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', 'Exam Period')], max_length=2)),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('duration', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDFDatabase.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField(choices=[('1', '1'), ('2', '1/2'), ('3', '2'), ('4', '2/3'), ('5', '3'), ('6', '1/2/3')], max_length=1)),
                ('week', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', 'Exam Period')], max_length=2)),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDFDatabase.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('9', '9')], max_length=1)),
                ('elective', models.TextField(choices=[('1', 'NE'), ('2', 'PE'), ('3', 'EO')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDFDatabase.Course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDFDatabase.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('1', 'Class Registrar'), ('2', 'Lecturer'), ('3', 'Assistant'), ('4', 'Marker')], max_length=1)),
                ('hours', models.IntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDFDatabase.Staff')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDFDatabase.Module')),
            ],
            options={
                'unique_together': {('assignee', 'module')},
            },
        ),
    ]
