# Generated by Django 2.2.5 on 2019-09-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=20)),
                ('semester', models.CharField(max_length=5)),
                ('elective', models.CharField(max_length=2)),
                ('level', models.CharField(max_length=1)),
                ('aims', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.TextField(blank=True, default='')),
                ('syllabus', models.TextField(blank=True, default='')),
                ('criteria', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('reading', models.TextField(blank=True, default='')),
                ('lecture_hours', models.IntegerField(default=0)),
                ('tutorial_hours', models.IntegerField(default=0)),
                ('assignment_hours', models.IntegerField(default=0)),
                ('lab_hours', models.IntegerField(default=0)),
                ('study_hours', models.IntegerField(default=0)),
                ('required_modules', models.ManyToManyField(blank=True, related_name='requirements', to='mdf_db_app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('forename', models.TextField()),
                ('surname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='2', max_length=1)),
                ('week', models.CharField(default='E', max_length=2)),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='2', max_length=1)),
                ('week', models.CharField(default='E', max_length=2)),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('duration', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='2', max_length=1)),
                ('week', models.CharField(default='E', max_length=2)),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=1)),
                ('elective', models.CharField(max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('hours', models.IntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Staff')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'unique_together': {('assignee', 'module')},
            },
        ),
    ]
