# Generated by Django 2.2.3 on 2019-07-22 10:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.TextField()),
                ('credits', models.IntegerField(default=20)),
                ('semester', django_mysql.models.EnumField(choices=[('1', '1'), ('1/2', '1/2'), ('2', '2'), ('2/3', '2/3'), ('3', '3'), ('3/1', '3/1'), ('1/2/3', '1/2/3')])),
                ('elective', django_mysql.models.EnumField(choices=[('NE', 'NE'), ('PE', 'PE'), ('EO', 'EO')])),
                ('level', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('aims', models.TextField()),
                ('syllabus', models.TextField()),
                ('comments', models.TextField()),
                ('reading', models.TextField()),
                ('total_hours', models.IntegerField()),
                ('lecture_hours', models.IntegerField()),
                ('tutorial_hours', models.IntegerField()),
                ('assignment_hours', models.IntegerField()),
                ('lab_hours', models.IntegerField()),
                ('study_hours', models.IntegerField()),
                ('required_modules', models.ManyToManyField(related_name='requirements', to='mdf_db_app.Module')),
            ],
        ),
    ]
