# Generated by Django 2.2.3 on 2019-08-13 12:09

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=20)),
                ('semester', django_mysql.models.EnumField(choices=[('1', '1'), ('1/2', '1/2'), ('2', '2'), ('2/3', '2/3'), ('3', '3'), ('3/1', '3/1'), ('1/2/3', '1/2/3')])),
                ('elective', django_mysql.models.EnumField(choices=[('NE', 'NE'), ('PE', 'PE'), ('EO', 'EO')])),
                ('level', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('aims', models.TextField(blank=True, default='')),
                ('learning_outcomes', models.TextField(blank=True, default='')),
                ('syllabus', models.TextField(blank=True, default='')),
                ('criteria', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('reading', models.TextField(blank=True, default='')),
                ('lecture_hours', models.IntegerField(default=0)),
                ('tutorial_hours', models.IntegerField(default=0)),
                ('assignment_hours', models.IntegerField(default=0)),
                ('lab_hours', models.IntegerField(default=0)),
                ('study_hours', models.IntegerField(default=0)),
                ('required_modules', models.ManyToManyField(blank=True, related_name='requirements', to='mdf_db_app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=10)),
                ('forename', models.TextField()),
                ('surname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2')),
                ('week', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Exam Period', 'Exam Period')], default='Exam Period')),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2')),
                ('week', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Exam Period', 'Exam Period')], default='Exam Period')),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('duration', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='2')),
                ('week', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Exam Period', 'Exam Period')], default='Exam Period')),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_mysql.models.EnumField(choices=[('Class Registrar', 'Class Registrar'), ('Lecturer', 'Lecturer'), ('Assistant', 'Assistant'), ('Marker', 'Marker')])),
                ('hours', models.IntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Staff')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
            options={
                'unique_together': {('assignee', 'module')},
            },
        ),
    ]
