# Generated by Django 2.2.3 on 2019-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='aims',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='assignment_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='lab_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='lecture_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='reading',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='required_modules',
            field=models.ManyToManyField(null=True, related_name='requirements', to='mdf_db_app.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='study_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='syllabus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='tutorial_hours',
            field=models.IntegerField(default=0),
        ),
    ]
