# Generated by Django 2.2.3 on 2019-08-14 09:27

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='week',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('E', 'E')], default='E'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='week',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('E', 'E')], default='E'),
        ),
        migrations.AlterField(
            model_name='project',
            name='week',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('E', 'E')], default='E'),
        ),
    ]
