# Generated by Django 2.2.4 on 2019-09-06 09:43

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0002_auto_20190814_1027'),
    ]

    operations = []
