# Generated by Django 2.2.3 on 2019-07-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0002_auto_20190722_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='required_modules',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='mdf_db_app.Module'),
        ),
    ]
