# Generated by Django 2.2.4 on 2019-09-06 09:47

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0003_auto_20190906_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', django_mysql.models.EnumField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
        ),
    ]
