# Generated by Django 2.2.3 on 2019-07-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0004_auto_20190722_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='aims',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='reading',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='syllabus',
            field=models.TextField(blank=True, default=''),
        ),
    ]
