# Generated by Django 2.2.4 on 2019-09-06 09:55

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0004_course_coursemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemembership',
            name='elective',
            field=django_mysql.models.EnumField(choices=[('NE', 'NE'), ('PE', 'PE'), ('EO', 'EO')]),
        ),
    ]
