# Generated by Django 2.2.3 on 2019-07-22 10:56

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0005_auto_20190722_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('Exam Period', 'Exam Period')])),
                ('weight', models.IntegerField(default=0)),
                ('information', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('coursework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mdf_db_app.Coursework')),
                ('duration', models.IntegerField()),
            ],
            bases=('mdf_db_app.coursework',),
        ),
    ]
