# Generated by Django 2.2.3 on 2019-07-23 09:40

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0006_coursework_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True)),
                ('forename', models.TextField()),
                ('surname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_mysql.models.EnumField(choices=[('Class Registrar', 'Class Registrar'), ('Lecturer', 'Lecturer'), ('Assistant', 'Assistant')])),
                ('hours', models.IntegerField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Staff')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdf_db_app.Module')),
            ],
        ),
    ]
