# Generated by Django 2.2.4 on 2019-09-06 10:00

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0005_auto_20190906_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('1/2', '1/2'), ('2', '2'), ('2/3', '2/3'), ('3', '3'), ('3/1', '3/1'), ('1/2/3', '1/2/3')]),
        ),
    ]
