# Generated by Django 2.2.3 on 2019-07-23 09:58

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0007_assignment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=django_mysql.models.EnumField(choices=[('Class Registrar', 'Class Registrar'), ('Lecturer', 'Lecturer'), ('Marker', 'Marker'), ('Assistant', 'Assistant')]),
        ),
    ]
