# Generated by Django 2.2.4 on 2019-09-12 10:28

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0007_auto_20190906_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemembership',
            name='level',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
        migrations.AlterField(
            model_name='module',
            name='elective',
            field=django_mysql.models.EnumField(choices=[('NE', 'NE'), ('PE', 'PE'), ('EO', 'EO')], default='NE'),
        ),
        migrations.AlterField(
            model_name='module',
            name='level',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1m'),
        ),
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('1/2', '1/2'), ('2', '2'), ('2/3', '2/3'), ('3', '3'), ('3/1', '3/1'), ('1/2/3', '1/2/3')], default='1/2'),
        ),
    ]
