# Generated by Django 2.2.4 on 2019-09-12 10:29

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdf_db_app', '0008_auto_20190912_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='level',
            field=django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1'),
        ),
    ]
